#!/usr/bin/env python

import rospy

from mqtt_bridge.action_bridge import ActionBridge

if __name__ == '__main__':
    rospy.init_node("action_bridge", anonymous=False)
    action_bridge = ActionBridge()

    try:
        action_bridge.mqtt_client.loop_forever()
    except KeyboardInterrupt:
        print("Shutting down")
