#!/usr/bin/env python

import rospy

from mqtt_bridge.state_action_bridges.action_bridge import ActionBridge

if __name__ == '__main__':
    rospy.init_node("action_bridge", anonymous=False)
    action_bridge = ActionBridge()

    rospy.on_shutdown(action_bridge.mqtt_client.disconnect)
    rospy.on_shutdown(action_bridge.mqtt_client.loop_stop)
    action_bridge.spin()
