#!/usr/bin/env python

import rospy

from mqtt_bridge.state_bridge import StateBridge

if __name__ == '__main__':
    rospy.init_node("state_bridge", anonymous=False)
    state_bridge = StateBridge()

    try:
        rospy.spin()
    except KeyboardInterrupt:
        print("Shutting down")
